In [62]:
import numpy as np
import torch

## Scalar Tensors

In [63]:
scalar_tensor = torch.tensor(27).type(torch.float32)
scalar_tensor

tensor(27.)

In [64]:
scalar_tensor.dim()

0

## Vector Tensors

In [65]:
vector_tensor = torch.tensor([17, 32, 28, 12, 57]).type(torch.float32)
vector_tensor

tensor([17., 32., 28., 12., 57.])

In [66]:
vector_tensor.dim()

1

## Matrix Tensors

In [67]:
matrix_tensor = torch.tensor([
    [12, 31, 15, 29],
    [16, 55, 38, 11],
    [19, 72, 43, 87]
                             ]).type(torch.float32)
matrix_tensor

tensor([[12., 31., 15., 29.],
        [16., 55., 38., 11.],
        [19., 72., 43., 87.]])

In [68]:
matrix_tensor.dim()

2

## 3+ Dimensional Tensors

In [70]:
three_dim_tensor = torch.tensor([
    [[11, 23], [34, 16]],
    [[19, 73], [98, 65]],
    [[34, 87], [52, 71]]
])
three_dim_tensor

tensor([[[11, 23],
         [34, 16]],

        [[19, 73],
         [98, 65]],

        [[34, 87],
         [52, 71]]])

In [71]:
three_dim_tensor.dim()

3

In [72]:
three_dim_tensor.shape

torch.Size([3, 2, 2])